apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-pass-test
  namespace: mysql
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: mysql-pass-test
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: dev-shopping/mysql
        property: password