---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-pass
  namespace: mysql
spec:
  encryptedData:
    password: AgB1qeye3Gy8+Vtn0jSmizHSk1ApOnLDcZhoUMudG5pXrwnAm1jeUaUH8PFf/Km9vWAmd9DPSrwkBm6Qdh84McoATiaKvWos4Qwn5ur4mT+RVWCdWzaVA2eIfzyU+moVHr/un3zxZJBp+iX7RD1d8EYwvtGE0UR3EsqpYEeUdBo5QxeMHdApVfkJbPW3fv21NuDDmmK1FW8Ylvwb4L47BQs5HXjBxnW/v6+kXfnvColBWfAEsjhjg2dXxUiOlEU9Eo+phj7ano2nqUunPOvfbk5jCWYEsCHbKUebdSw4NEzN2u7Pra8WXTq69TPdSL2nkh86WrrBid6R9ewlXUL8uDWc4t6VIAnRVNIqGW9MZU7O0BEiQjdj4KVubMbK/1OeNQbsqebVcQOSFvidzGqcOFdIhR7dKWWoc5FUZhwjHsGwPJfhixckEfXgjmVbBJxPFZXTvY4fA1AJLFQ2D3YGfKQWaYB+6JIgD4FmaQYKtYh5AD6tNtNHj0wOvyoRgnsGiU1ZqMCrF0heShS+9IGTfEXwg/tOyaOFId5fSmIVywQSJD9DITFUQUV+WwH+KxkXne+zq+a2QRC+hA1xGi1YjNDJWyetG/kd2NYSFYX8rkCytZpdbxbNB+P8JjcLer8/mTYUOb4GBg/bD4/ggHhDOONPBq1th1Nnly1U+k9OQduKuUir1I4dsNWoJOxXGo3/WA4bTaEbJu+2WA==
  template:
    metadata:
      name: mysql-pass
      namespace: mysql
