---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-pass
  namespace: default
spec:
  encryptedData:
    password: AgCFjFaPoJvci0ktDQfAapFzSgb03UAPiAGLg6JK+Qg2g4KD821Drp/Z9198wLgZLpnO4G80UjENj5743MQimH9T5LmIVKrEv4l7jg0qsSjKcXKin3lHiPlwIC8BKWWEx0AIPnOSOoqkNguvjT9TpgByhtxQaOe1sB9CreG2BglCx+I4mjUa7aSRjObEHuItCx0jGoAV58VygqLNJmIOJGiPIr1M5z0GIPnGXKG2kA8fMlSkC5nmJJs0vnfW1pc5n13FuhjCTAn0oKV/rHAlhkxmdQqHHGBkuhCcbx3dmRPeJ6iX+tLdgTYUzF33aFy+61FG4h8e6OMSp20ZMqBEOqefpa2UhIqgBUfoI7uyjy+5+XvrhY4nNN1JBYEuzx+/TFtTe52VXMcCciqUgIlNFPM23ExDlw227Tc+3rVTegqEPjhZLD+ycdQJU70rFx7EMyQ6J5JXZ/Mxj5Q2eQPU4UJ7wjPvgi86ORsK1NHvmktXlev8VN5n5mwBNSE5wqRaApxhnjZoFT6lUJOKYsZuu9D2RLMK+xnc5kSCZNd1ogC9X2lEB2YxQIpu6atOH6PT65+Ed6e+RB/KMy4zBe9ydP1kgt4RswzLjxZyo/mAqb8ljLtn6dVKNuRg2PAw9LGvbciJzD8zcn3rDLu7Dghd4CPfNA7otR92ZvbrdPWQT3soB0hCyC7bYNq6CkShA4LRG9CRrXnmxDoMaQ==
  template:
    metadata:
      name: mysql-pass
      namespace: default
