---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-pass
  namespace: mysql
spec:
  encryptedData:
    password: AgBqoiik+mi7x1Fc+YYZ4Hqg2xhORZWfBS8allbQzB14Hep0eCM6FrXap70/xbFSPew2Tep0lXFrT96QY0r66hJw2CbTfCpyY7zsd2Q4JXJOT5IOP4pb146LMUl/tZoGZBz1Yzz7O3eIdG/5XKmukSJruXk90ZhUd53QI/zzLyq6cWXmUhZDVfkjvFU7Q9o/ut+cq/f6a3hPOsTXTv+HGPkARFCbpyoG2bvtpWfAAktA19QSMfLrRrRQQP+gDxyej2ZM4sP5STVaYikulVpaybVyIB/nhbnhNUCMH3ErkXmgqf45Kt+6+A+6bZthnAiU29O+cMaQta2PVbLlkFB+9lnWdvyU0XirwAVI23NfLJTtTxXZfUlHy0kzeiBwOgw/ixRQBkdn9B4CZ0jImQ6mgwKUL7qKNAPXX6QY7Lp2vokZZNZLsO2zLpnj6MheSWBpA/wNHioZEliRH76iRHHxLD1KdpIA2+d96mpr5bwjlI4r0mh1oFGT+cI3NsFW70eypu4PuORaaL/chW+MZuMBd9NzlVr/upXz5VZqaS29qYVRbekGHniwMYX+icitcZaG1l43qdIOywLXavXsEwy7UFxUtGgpGOZuvo7U8+SkpQIHkaPWJMAeEnNTI6XLJ0lEFuK2BdCKhPtieraQHA4K+bLXgndzFwZs/xrXXGZxdVyAptMeQzLRlknyAZ1D6x6IYjV0Z+NL6w8tmQ==
  template:
    metadata:
      name: mysql-pass
      namespace: mysql
    type: Opaque
