---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-pass
  namespace: mysql
spec:
  encryptedData:
    password: AgCT4o0sm3uxNxsl9scQWp4YJUBAxnW64n+mt0Kyi8acAHddKVUjlJnn1Lvu/jJc3IWp0aVOJw97U0oZgOCzmCvVrjTRqR7I3YDKA8mu+5oqdXol34OigqOMVSsxPthbZbKeOwKIwO69SObBtfI8cZuUgTrPQLRVUKUZBfH9hQGH9ebptFwejjMDuhaaKd1kGtcBdjOalyCj32SVGBOkunAJztXWGrnmoEdz44KRDqi/LUF3YEBzXuHWBiioXxZgCLwDVbfwZEDZGD/yRlr6/W3rOzKnzd/GV3yNoXxQGJzYaECcA/qCX/452LmZAkM9l/s4Wz+lsJAxr0GOCGOyuKN+dwdzH10NhN5a0up3jdDjCScMPBW4FyAj1S8YH7M+V5lE40xD+36NpwYBEOZRpwLut7M/aIQdQXEcXiCVIoEGp82I9oRl54teymsbv8aNRX3pyPoZKYjKNh3t4cgSEKux9h0i/0/Bz1ImNU1yXAUWPCKjzZOEZnbo/RuDioaktpMEVDWu8nwTJyFMunm5kU8WAc45l1hKWSjIfok/G3aTMVZ4nLVCHS+ekIQtP/Ox1HSWOtKIDzNvAhPRvYDdjTEd76wXmAHtIKo068JfJZIqCDcHnaZAhL/MfSUhHpsoorA5sRQgdy4/HvVw1I3/gkUSf3KhYm6u+GDBuz17tFXSVGtshUiMWx10BSurTr2VZ4DkA03TC8QGIg==
  template:
    metadata:
      name: mysql-pass
      namespace: mysql
    type: Opaque
