apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shopping-db-secret
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: shopping-db-secret
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: dev-shopping/mysql
        property: databaseUrl