replicaCount: 2

image:
  repository: rarestomuta/shopping-app
  tag: "70ca939ea59fa3d0f3b57190ea464b03f2239b6d"
  pullPolicy: IfNotPresent

frontend:
  image:
    repository: rarestomuta/shopping-frontend
    pullPolicy: IfNotPresent
<<<<<<< HEAD
<<<<<<< HEAD
    #tag: "15844013013174493dc6e3fa2cbbc569016b69ed"
=======
    tag: "f14a56805066a21fed9f3fa2725dcdd13cfb3afa"
>>>>>>> b81c30c17c309f197b5a8fd47b8a18e1c24a86ae
=======
    tag: "70ca939ea59fa3d0f3b57190ea464b03f2239b6d"
>>>>>>> e8a126e227ac6ee8d15150501e55f3f5b35693f6

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: shopping.local
  tlsSecret: shopping-tls-secret

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

env:
  databaseUrl: "mysql+mysqlconnector://user:userpass@mysql.mysql.svc.cluster.local:3306/shopping"
  keycloakIssuer: "https://auth.local/auth/realms/devops-lvlup"
  keycloakJwksUrl: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/devops-lvlup/protocol/openid-connect/certs"
  lokiUrl: "http://observability-stack-loki.observability.svc.cluster.local:3100/loki/api/v1/push"
  serviceName: "shopping-app"
  environment: "local"
  otelExporterOtlpEndpoint: "http://observability-stack-tempo.observability.svc.cluster.local:4318"
  otelServiceName: "shopping-app"
