replicaCount: 2

image:
  repository: rarestomuta/shopping-app
  tag: "afdfdb7f3a11c4f688152dc61094060468dc4118"
  pullPolicy: IfNotPresent

frontend:
  image:
    repository: rarestomuta/shopping-frontend
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: shopping.local
  tlsSecret: shopping-tls-secret

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

env:
  databaseUrl: "mysql+mysqlconnector://user:userpass@mysql.mysql.svc.cluster.local:3306/shopping"
