replicaCount: 2

image:
  repository: rarestomuta/shopping-app
  tag: "6e59030bd660c41da77a751818caa1db33c391dd"
  pullPolicy: IfNotPresent

frontend:
  image:
    repository: rarestomuta/shopping-frontend
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: shopping.local
  tlsSecret: shopping-tls-secret

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

env:
  databaseUrl: "mysql+mysqlconnector://user:userpass@mysql.mysql.svc.cluster.local:3306/shopping"
