---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgAvgjA0ZKBGw88CM4nhuw1fFdV3sNrOFZxuHTyQ5MciwF8pY18nqg3WbWHyU04ZHuSEbAzatdtd5t9CJijYZRZyfG5e9+GAYAZrqoj0E9gLyvn5t3P/gZBy5FK3BRzxs21rascdNFaqa+5ERekTKDzKqvk6ornX6kGP4/JVpeq5FE30ljT2eRtLYqb5Az3YggYt1PnKDPYKBu93pNGLTM1r2NKe9eByLYAKln84MD/aWx61Ush09cV7ISiZ4qXQhiVqwr6hWFEmkQza7+CEbskIq8Q1WaNKSTivPI7bGwQTUVWZymEsEWwgri79C05QwySGDSP+6pEJsn7mF0EHeCyZVE1L61Ak/gW0dxST9gPB5EfGeyPte+bupawEHNSEcJ6HMv4WiTfXTa+XQUH8+aDchTs8crHn+4hkSI1YT8jwLUf6RY1WkrZ5AM/svSonn1ZB2P99DFnTrkw38l4t40MG4MBh5yw4zEnSKiOa8IHwtUYU8sihjf0KIW0/ilWaNCIrRSVJwvkFCKTWb9hI4SHxhntDqfd/1s7vd/pAFGUlBIjimiiRTdamFXZaqAvQBQVyy2XTVFG9+0WSpEzQH8IUUpoiZtl6v45XWPKkwwRsqhNO1yUkKiDTY7zgtQqQrfMggs1pYMKj5TNOq2bl/NGoIGOKDr0ky+5bdy+JJ+/pmqYuYcCBb1ruNIUYAh1YooPz2RkCc+dPf7qUXIA=
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque
