---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBpGOnbCqKTFh+v0j7AoJeU/raIqH7R5oynJPHl70qLvpdc/Qgfs7OktrR9WNE47xuCITIwrShRmRHGXYfJ2vMdjjMOrTxONzA5WeHbiEemP8Ow5JY8k45fbCzHtE2kXd7jw49rMGZ9nzPorUOmFjEX2ubnRjulDh4bPO/FfCkYdf4/+f+hywJAozHNC/kkPOokQlgXafKAavbY4nG3PaPDKhnoSK1QV77bGmkBy6+1V/mfwaS/yvtwgy0IYeQvHz9hB3AsrLJ/vC+49YpnS6D3ZaRL4NscGWeIOEb4gF1pA4YqXT/6ieKTTmm7zJFfwUD/FUxpIaozc5IL81LWI+YwcJZpOp9RWx9mD9MHCjv2kqCOJJYWZT2/y4c1pyYamrwcDVkaw1FSU5bErropPuNTZvcbSWRjvuOZUNTk81ug080fpdBKvcbkO0WvRnWTHhh64CBJuAipY4v/kwKDSXsfiNihtd61mjh1JdzSCzYDyYNpKcnfl8Us+oa1erfDJN1K87oSM6ZAy5O+zZ/2SxgO8ruuK+7vMt1PV0gw1q53b3y/6ko60NcUKN9EccNGruDrBjnFa0NuLB6ldU25AWdwfA569hVqp3E2XLHj6f5kvfbanaXnjet+3SOdbCxayk3GV5OPvmwJApKGIGagj5ae3n9HT1tzvwlm9HyzdxAgfER4KC7qKCHyiqaX9yv+TMhTVjjsHg==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
