---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgAem5PlG17j/TW5Ixu/E+tI6iAt79lXjF0dssYZKRaoN38Y/qr1VZGPMsGEe+3SO5Wt/Z8WlIZB7rN9RtK4istN+UhNbCtdxGzrIXQyewqQI4td+h+0BcdXxCKfi0iLm44GfxngOdCyvd95wDqq78ycRcZVY3Frm7gOZo8vti2Ma8XllADSWJ5n2nzk0FPQlAaiJMQUUEWQaGz+tZkZ/xTlB013XueNA76tZ44rQih2+R6MUm6ib4S8oUz4xHi4/UoCYra/iR7qzwho8X/+WU7wH41CsFeKHmSw2/Vu8noitDyzzNpsdM7zKkp/xISQqF1phv5DGIscrw/5TIoHeP/BcdC6gMukRY7rrtvLgr7wqa9ApTAeHCqmsa+LrWtFsyZL5rMvNXRp8Epru7n4saA9zoUWzNI5dHyP4gV7M+VNwCb+62X9XpTp9//adKpDwT+RJiYioIZr7MZ3rCbXFFIkqWmBDg+zWFk5WCshjlwHoLpFMFaYxudbAb+zURZU51TGbOa1dkC66cmlSYVXTTgzvdpIGltYyx60ft8DUcGhVJ02FoHHXiSdG8k9AyWAmDcLChA6lo8UxXpr6sdDC4BX+7vixQulJs0W+r0XACgxcj/UD2TybH3eUu7ulxGKsrMSY6TkoTWNGJTqR0xejeSNFvjJABQfOH0O/utm/a2zeqH/PI9pgU+zYQd1RsBHG1vMqUraBH8ehJ+5xTQ=
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
