---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBJPntODsb2DecHSN/kkeddQeSUw+GHwg/XS5YXl/jojGlyAygElCgZi70xNXl21TBCxhPv1JdeGnvV02K56jzQlbANDJ7BaaJSdNXrSiQHo0ztPkgvhS0twbGu+NCEW0vbFEz+AWvDLEGvs8opsxpD5Y1EplZFB2Ez/Ex+n/tHckfQpS5Rg2Jwx3T7gdNmuThtXB3cvawjqi4KdIBubHnakEZRsCI/OSQk5vg7SmH+Gn9r01KMn/gp4Z0lJVeSp6i/z+vidhaytUD7e2KQl272kmdMV7T0eRnbjLd20A+8mcYAacsklXAJUbh0yHQ6iE6KFrliCymtyR7wug8qhTL27Z8TEw7gAtlMK97vzjY/7mPTQB3uvPeFWHq3bWC6ePF/D8e/0DZrAt9KgYDQTPCb52lJ7r+obFEbt6ze7or+7cwS3gTgejMhR3oPErQgmpi+FHuUOSB+todswm8reMV6291XYI+dyZL56jsOuBsrBlbjer7yxH63KlxxKlmxTmfZcdHet2LXUWy8KIl5xYzvFo35P4No/Uv8pWRO6M2f6ujszvTfgzrmXgnbl5NgCORx/NTus/g0QOl8nhKlnLROhqSrUZkWskYBn0iS60gf5o9+lagvYZrgcT1uIJZbE/F3iSomEzMJfzTsW9Hd6f1w+PcrQ5Zs7tiMXKkJ/5b/jT9P0QlOEyvukW9x3w2ttJu5gWH9Vis=
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
    type: Opaque
