---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgArUfqwbWHnWXe4VNe1pkGn60W3TLeamBmbcz1NTmDfftKe70PuspKM9B9moAUm8VD2GcZKXkoQGgYdi8uT2S02a+5XMwGuQMSURH5k4SudsZ/pIHhudTVtXcvnptdMLHHIQd38gbRHnasXx2Hf7AAh81yfinaAOBiIpoIP76PNM550yqRg3VJR387HCkTePOPWeELrAtgSVo+H5wSNAxi4+Voxif7S9nbAI9JGEGo6neOyiBVVSugddbwiBxLLCag7GRHuaIjXUqejV/vP3TKaJJPtECUqz79EqCcLff6lyMZpryygFuLeTXYqHbKbzl7EaLj2uy4xpwWW9DmWEjHj3pD6AV0o9WhEyUBcBgEF+Kqvk4HJu+i1mIxvdGUJOQwOCQqu6Bjt4B+FsFPjc9FwGTY1qyRZzRg/aqXlGLKhfJX04pfh3P/Hr4vspz9tLCAwQROSZUbd+FjEveCl0Fg8vgV1FjTZkj5Ser6TyTRhm+5/yht6sM0D4Bl2iy16znJ45GP9tV1AiqMVJMYGjenQTkkUKw/RP1XDHfeMNwvrCCsphgw6KbbOqg3kFxnak4DlHTHUvqc6h5rbNgFjig/iYMdS8rr41fs9knHtIISKTk+vpTjny1iK3K/LI071gST0LpaqAoUztONjo2whvqCKjx24gncDS+p7XqcODSsUot+3J7DOJDae2MhnoieEU1AmrcUAxu6868aHKxA=
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
