---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBGu6nZX4oAozZUWDFWHW517aPczv+IOXKFCuWQIXZgo+7ilrNIotJX6QG0CKobqT4ysOySjjve3IDuOdppDHp97Q0kVgBrr5rGAt4kGFRIgCUZ2u1ApiEZlunbI/vRmqoXe1M2bQIms3GbBr2nY937+kwjWvLT74YvHeAIYSTi5FERQcAg7Sc1FfHvOLe6FJHN/2Td7bwgt9bKBX7ltrUQDAqRNfz1TXms1aP7ZpF8cKabHnnxLUNreWvciNCMkUOamZYF6SuskFLjjuPBGjeSSDt/vHw4jk9oixUlSNOSPnTrrrzDJ31Il6Zvex/nQtubyvRHrvGxcdQTdgBefKY1VX/3JHIlkgqDIgVZig9rMUeYfdyyJxzNNbLX0Wg+0q+VfPZvRmz3BgbEWK+AHwXiQ7G09SlB4IJp8y2a8pZw+Rvtehsc5n9rS90w2hfDduTJJz60TJrgQFK1XUEJf8CQ6YuY47680NF9sIseGjGoy3HC3EdfzhbW2jz8k+7yt9qxwBwKYXGq/ANR2Nj1uDsU9CYr5RPNK80YYkZ/h5hoIOfbg/n5y+Q+L+M6l5RDj1OCjS0BBlgRlGetrsbHD6Cc+3SKkCO23LhzjRcmRxHIduOYDQ7FKG5Mbz4YSR6IweRUyUMtTkuvn17UMQ2+uiTM5NnoTR8OKgtl++XSW7RFRRGiRwB8iXaEAA9w6runnGjDgIdNTQ==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
