apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: mysql
spec:
  encryptedData:
    password: {{ .Values.secret.encryptedPassword }}
  template:
    metadata:
      name: {{ .Values.secret.name }}