{
 "title": "SLI/SLO dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Availability SLI - 7d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  1 -\r\n  (\r\n    (\r\n      sum(increase(shopping_http_requests_total{status_code=~\"5..\"}[7d]))\r\n      or vector(0)\r\n    )\r\n    /\r\n    sum(increase(shopping_http_requests_total[7d]))\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLI <= 500ms - 7d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    increase(\r\n      shopping_http_request_duration_seconds_bucket{le=\"0.5\"}[7d]\r\n    )\r\n  )\r\n  /\r\n  sum(\r\n    increase(\r\n      shopping_http_request_duration_seconds_bucket{le=\"+Inf\"}[7d]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Error Budget Consumed - 7d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  (\r\n    (\r\n      sum(increase(shopping_http_requests_total{status_code=~\"5..\"}[7d]))\r\n      or vector(0)\r\n    )\r\n    /\r\n    sum(increase(shopping_http_requests_total[7d]))\r\n  )\r\n  /\r\n  0.001\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Error Budget Consumed - 7d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  (\r\n    1 -\r\n    (\r\n      sum(\r\n        increase(\r\n          shopping_http_request_duration_seconds_bucket{le=\"0.5\"}[7d]\r\n        )\r\n      )\r\n      /\r\n      sum(\r\n        increase(\r\n          shopping_http_request_duration_seconds_bucket{le=\"+Inf\"}[7d]\r\n        )\r\n      )\r\n    )\r\n  )\r\n  /\r\n  0.05\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate - 5m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  (\r\n    sum(rate(shopping_http_requests_total{status_code=~\"5..\"}[5m]))\r\n    or vector(0)\r\n  )\r\n  /\r\n  sum(rate(shopping_http_requests_total[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Requests > 500ms - 5m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  1 -\r\n  (\r\n    sum(\r\n      rate(\r\n        shopping_http_request_duration_seconds_bucket{le=\"0.5\"}[5m]\r\n      )\r\n    )\r\n    /\r\n    sum(\r\n      rate(\r\n        shopping_http_request_duration_seconds_bucket{le=\"+Inf\"}[5m]\r\n      )\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}