loki:
  enabled: true

  deploymentMode: SingleBinary

  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage:
      type: filesystem
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin

  singleBinary:
    replicas: 1

  chunksCache:
    enabled: false

  resultsCache:
    enabled: false

  gateway:
    enabled: false

  backend:
    replicas: 0

  read:
    replicas: 0

  write:
    replicas: 0

  lokiCanary:
    enabled: false

  test:
    enabled: false

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  service:
    type: ClusterIP

  persistence:
    enabled: false

  testFramework:
    enabled: false

promtail:
  enabled: true

  config:
    clients:
      - url: http://observability-stack-loki:3100/loki/api/v1/push