loki:
  enabled: true

  deploymentMode: SingleBinary

  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage:
      type: filesystem
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin

  singleBinary:
    replicas: 1

  chunksCache:
    enabled: false

  resultsCache:
    enabled: false

  gateway:
    enabled: false

  backend:
    replicas: 0

  read:
    replicas: 0

  write:
    replicas: 0

  lokiCanary:
    enabled: false

  test:
    enabled: false

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  service:
    type: ClusterIP

  persistence:
    enabled: false

  testFramework:
    enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://observability-stack-loki.observability.svc.cluster.local:3100
          isDefault: true
        
        - name: Tempo
          type: tempo
          access: proxy
          url: http://observability-stack-tempo:3100

tempo:
  enabled: true

  tempo:
    auth_enabled: false

  persistence:
    enabled: false

  service:
    type: ClusterIP

  resources: {}

# fluent-bit:
#   enabled: true

#   testFramework:
#     enabled: false

#   config:
#     service: |
#       [SERVICE]
#           Daemon Off
#           Flush 1
#           Log_Level info
#           Parsers_File parsers.conf
#           HTTP_Server On
#           HTTP_Listen 0.0.0.0
#           HTTP_Port 2020

#     inputs: |
#       [INPUT]
#           Name tail
#           Path /var/log/containers/*shopping-app-*_default_shopping-*.log
#           multiline.parser docker, cri
#           Tag kube.shopping.backend
#           Mem_Buf_Limit 5MB
#           Skip_Long_Lines On

#     filters: |
#       [FILTER]
#           Name kubernetes
#           Match kube.*
#           Merge_Log On
#           Keep_Log On
#           Kube_Tag_Prefix kube.var.log.containers.

#     outputs: |
#       [OUTPUT]
#           Name loki
#           Match kube.*
#           Host observability-stack-loki
#           Port 3100
#           Labels job=fluent-bit
#           Line_Format json