image:
  repository: mysql
  tag: "8.0"

mysql:
  rootPassword: rootpass
  database: shopping
  user: user
  password: userpass

service:
  port: 3306

persistence:
  size: 1Gi

secret:
  name: mysql-pass
  encryptedPassword: AgCNgK+oBXuzF77oYBa2vFFj1+sV9WsmSv2/PpUDaEan4pEn3+sENNVRsFTGLkda7TGElUskUUsJhKjviL6xh3XBnfv7SMCoX/vh1tUJjU9wnWjXWlZYq3O3sFXSvSDZL15iKjRPwITU7cXEZOP+hl8vUBTUjnj3WGF1rOorTXcCohXn1kHixHkZ1f6uUCAzowjfIU4rh3d0ijGCEHvQTMtdXfKXHsaBUJRNN0xLbEPx/K5gAJI8x8YaaMSiRfm3xamQWWP5I20CbBAeJbSxTBooK3v2yVyG/Y7TzyVzgnaJDYIcnL40OYFrS1p/wN5JpR5pkoQPLAmiz5td33nGxNpCJWxFwgpa3MgsXK3ESM8VN6ahVjdZIY4HuZhkXgGvYGTOkC19hiagzQBBIqCZaiAMXMlYUKN95z/X/tY3M3235kjPQtJIw2fOPBNwaqxq1fDU4+zHQ7U2G6vgm9pDaNnn3vW1P2JbaLki7Ry1G2LoPYe188zbk9F7z5eHZ1CqSpnMth6PhbQYGR0tjQpjfhjswvezu8+iaXxLXKzQoKR+N7osLJSyr5r9tvH7glYfCTDT328ptrmHhOSlcEkDLHmNRTqeSfaT3LfFVk1aonztydTw4OxK7Jk+58HmGGLqS35BN8ctOdqMTapLq1kKzN/GgXH/S0GYDgJTH4WFPVjW4kWfWLNx9m0wFU4pzVjzXMsxnXf3ZcZOVA==