image:
  repository: mysql
  tag: "8.0"

mysql:
  rootPassword: rootpass
  database: shopping
  user: user
  password: userpass

service:
  port: 3306

persistence:
  size: 1Gi

secret:
  name: mysql-pass
  encryptedPassword: AgBo3Kyw79opvX+yByJtBF/tM1Q/zfuZ7REYmQP7wVcO6lIrWey/q1Q2Xe0iwQ1qIqLxYNYN1Os2QRiAhoV9xV56I9ItdaZzhdIRtVPC2OpSRTDQHOGuHSnpKYKMiDZt7kWrMnUefSSqmaENMiPlS/exY/DkfI32GsZWW+TnD+gLFlOTr7Zq7KclgnohJpfunZZ8T3g6/57oDCqkDNCad/aJ3Qc5oX55xxxajSUm6XfHEsYFy0FDpyGTHohlNz9iYFpoePD7d82BGhia98dtCEjHmmgPGJXNwh87FdRZM4KOYYAZsDDhNTGPflMB6dbsOpLiPTCTDR+ObWkh7k90NA1jY05QuMaYsa5mzmJyQIEl9jmCOtmBmLYfkM8U4gaJqnpxyiUdCfGeTtZeqFJGhrF62DGJQAvcohl7xJ1Z5Gwiyl9D5JtbFIl1IV0i/p7M9nep51mva6hhcNRKOsbl02R2avJvSCDBVxvhLmmRmlosmAuSBfehSjrRxSD9Z+X22sZ5O8XBnrtN+/f5BJFVkl8PXJ+JpDvE9fZ96Mh7qpmhZiDMAPPyVkOrUUBejRfYM0q4zfFNerwQLCqrAOJR9XFVq8aVLGCAe82z8pAzvnVO0Oo9e/9Ma8nyj4pi5OSj2OAX0uMAbiJxhOy6eUJ2NR+6vaCO1mKes1o2rew9GkgJo+R/XdalWRmGSjqE8rIZAa87GA8W5GG5og==