image:
  repository: mysql
  tag: "8.0"

mysql:
  rootPassword: rootpass
  database: shopping
  user: user
  password: userpass

service:
  port: 3306

persistence:
  size: 1Gi

secret:
  name: mysql-pass
  encryptedPassword: AgBfrqwfP+eq4ZmngYTacvyEN4g+KFVAuCoH7TEHqkZeFHMl84g9/taQN4TMSHOHPavOWfO8V2uE6w+PVWh4+3IhIBE8d35DdqKhXasnH8hVCgSWHICuyxR+myc5aYyHIMKVxHQxa1jb2WrRyY0QhwVeGqYlikeaMdm63sYBmHW1hpWom3DiQMJqdd2X+TJzfSSt4vtvUTisOpc3FGBK0gMECthyp5Iq955/ZAQJZqiRdla/VpqReHybyy6LwwetNb8xf/rtaTbxhxB45D0YEfQwlOya844FJXRNZvCQ7xoVz2YKGgMUsQ6NKsS8UGfk97GaYTi5U9Pds57enyCH6MZrCe4IQ3PCtWd+02YsIMV7jWH9eibHQkiLX1DpMuEuZYd4Neo17FJlC5el2fwH36pqUOmnROZsYoGMu6UBEyMbk0hmJVsgw2P7w+fK0myqjbjS+G14RhAAW5rSsjYBUDZQ03Rp+icU4wPDd2cKQVldk6SZGaLj0sLExqaeJhw13X/sIqMRkO+U0Y8MHlbQD3M8WabSbqKxJA0oaBa6sOm1/uX3udnrj/U85EDxlCApWy3nQ4gfijtQqnGslBBltbtGIjwI50/3DtU1lli5bVAEji9ZggrHlEjFlFtj+26H8887Sj2uUXimw6PR9reMvFBRbZx1UZgm75YRC5p9FQ3Ze87wz+2CrnhG4huWd9dIIKr3OiSCJi0WcQ==