apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-dev-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Local Dev Root CA
  secretName: local-dev-root-ca-secret
  duration: 87600h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer