apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shopping-tls
  namespace: shopping
spec:
  secretName: shopping-tls-secret
  dnsNames:
    - shopping.benchpressproiectradu.ro
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  secretName: keycloak-tls-secret
  dnsNames:
    - auth.benchpressproiectradu.ro
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: observability
spec:
  secretName: grafana-tls-secret
  dnsNames:
    - grafana.benchpressproiectradu.ro
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  dnsNames:
    - argocd.benchpressproiectradu.ro
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer